### ISSUE TITLE
Tests fail on Windows

### ISSUE THREAD

**Issue by oravecz** [ringo/ringojs#106]
The path separator is not taken into consideration on Windows, so nine tests fail because of this. Also, there is one test which performs a file size check, but on Windows the file is larger because an EOL character is CR/LF on windows. 

I've addressed these issues in a patch I will attach (once I figure out how to do so with git). I added a function to files.js which simply replaces backslashes with forward slashes for test assertion use. Files.js may not be the best place for this, so it should be moved to a test-only scoped module. I would of made it a special type of assertion, but that seemed to heavy handed.

There is one test that still fails because I am unsure how to address it.

    exports.testResolveId = function () {
        // Child must start w/ ".".
        assert.strictEqual(
            files.normalizePathSeparator(fs.resolve(PARENT, VALID_CHILD)),
            files.normalizePathSeparator(files.resolveId(PARENT, VALID_CHILD))
        ); 
    }

Results in *`Expected "/home/ringo/Projects", got "home/ringo/Projects"`*

**Comment by botic** [comment]
I close this issue due its age and the tests are all green now.
