### ISSUE TITLE
Add helper functions to ease loading of JARs for package authors

### ISSUE THREAD

**Issue by earl** [ringo/ringojs#156]
Currently, it is less than obvious for package authors how they should package and handle required JAR files.

Our recommended approach currently boils down to using one `addToClassPath(module.resolve(...))` for each library. This is not only also is not that obvious to figure out, it's also cumbersome if you want to load many JARs.

I therefore suggest some helper functions for package-relative loading of a single JAR as well as a directory of JARs. This should be bundled with core Ringo. A good place to put those functions would probably be a `ringo/package` module.

**Comment by botic** [comment]
JAR resources can now be described in the package.json descriptor. They will be loaded by the module loader. c7725969a2e8201842a5bc82d891fda04e2c4232 should fix this issue.
