### ISSUE TITLE
allow module.singleton(id, object)

### ISSUE THREAD

**Issue by oberhamsi** [ringo/ringojs#171]
would be convenient if module.singleton() allowed me to pass an object as 2nd argument, not only a function.

currently i have to write:

    module.singleton("foo", function() { return {"bar": "baz"}; })

when i mean to say:

   module.singleton("foo", {"bar": "baz"})

**Comment by botic** [comment]
I close this issue now since there exists a first (work in progress) PR for this and the discussion should continue there.
