### ISSUE TITLE
 containing meta-inf/context.xml cause java.io.FileNotFoundException

### ISSUE THREAD

**Issue by ghost** [ringo/ringojs#177]
If meta-inf/context.xml is added to my webproject which is based on geoexplorer which is using ringojs I get an error opening a page in the browser. JsgiServlet.init() is for some reason looking for a modules cataloge under \bin of my tomcat installation and not under /webapp/.

This happens when my project contains a /meta-inf/context.xml with content:
<?xml version="1.0" encoding="UTF-8"?>
<Context antiJARLocking="true" path=""/>

When deployed a conf/Catalina/localhost/geoexplorer.xml file is created.

and I get the stacktrace: 
javax.servlet.ServletException: java.io.FileNotFoundException: File 'C:\apache-tomcat-6.0.29\bin\modules' does not exist.
    org.ringojs.jsgi.JsgiServlet.init(JsgiServlet.java:103)
    org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
    org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:298)
    org.apache.coyote.http11.Http11AprProcessor.process(Http11AprProcessor.java:861)
    org.apache.coyote.http11.Http11AprProtocol$Http11ConnectionHandler.process(Http11AprProtocol.java:579)
    org.apache.tomcat.util.net.AprEndpoint$Worker.run(AprEndpoint.java:1584)
    java.lang.Thread.run(Thread.java:619)

root cause

java.io.FileNotFoundException: File 'C:\apache-tomcat-6.0.29\bin\modules' does not exist.
    org.ringojs.tools.RingoConfiguration.resolveRootRepository(RingoConfiguration.java:176)
    org.ringojs.tools.RingoConfiguration.<init>(RingoConfiguration.java:102)
    org.ringojs.jsgi.JsgiServlet.init(JsgiServlet.java:90)
    org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
    org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:298)
    org.apache.coyote.http11.Http11AprProcessor.process(Http11AprProcessor.java:861)
    org.apache.coyote.http11.Http11AprProtocol$Http11ConnectionHandler.process(Http11AprProtocol.java:579)
    org.apache.tomcat.util.net.AprEndpoint$Worker.run(AprEndpoint.java:1584)
    java.lang.Thread.run(Thread.java:619)

**Comment by botic** [comment]
I’m closing this issue because it has been inactive for a long time. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this / there is no interest in it.

Please reopen if you still encounter this issue with the current master version or there is a need to address this issue.
