### ISSUE TITLE
httpserver module calls logging.setConfig()

### ISSUE THREAD

**Issue by grob** [ringo/ringojs#187]
httpserver module calls `logging.setConfig()` if it finds a log4j.properties file (in [line 424](https://github.com/ringo/ringojs/blob/master/modules/ringo/httpserver.js#L424)).

while this is certainly convenient in some cases it is cumbersome if one calls `logging.setConfig()` in an application before starting the httpserver programmatically (using `main()`), as it silently changes the logging configuration.

possible solutions:
- remove the call of `setConfig()` in httpserver module. i tend to think of it as too much magic, but i might be wrong.
- change `setConfig()` in logging module to allow only a single call (plus display a warning if the method is called multiple times). i don't know if there's a need for multiple logging configurations within a single ringojs app.
- export `configured` property (or eg. a new method `isConfigured()`) to allow modules (ie. httpserver) to check before calling `setConfig()`

**Comment by botic** [comment]
:+1:
