### ISSUE TITLE
a Deferred object can't be jsDumped

### ISSUE THREAD

**Issue by jgabios** [ringo/ringojs#195]
Running this code:
```javascript
var {Deferred} = require("ringo/promise");
var {jsDump} = require("test");

var cache = {
	"key": new Deferred()
};

print(jsDump(cache));
```
gets you this:

TypeError: Method "toSource" called on incompatible object.
	at test.js:52 (jsDump)
	at test.js:61 (jsDump)
	at test.js:61 (jsDump)
	at /home/gabios/code/zupazip/testy.js:8

same happens for this code too:
```javascript
var {Deferred} = require("ringo/promise");
var {jsDump} = require("test");

var deferred = new Deferred();
var cache = {
	"key": deferred.promise
};

print(jsDump(cache));
```

So i guess there is something wrong with detecting the promises.

**Comment by botic** [comment]
Closed. Rhino has a fix now.

https://github.com/mozilla/rhino/commit/430456ff2fb0edfa2b74c67248d44f8e4b48b923
