### ISSUE TITLE
"ringo-admin create" doesn't work for me

### ISSUE THREAD

**Issue by pluspingya** [ringo/ringojs#220]
I did 
   git clone ...(this repo)
   ant update
   ant jar
   ant clean
(All build successfully)

set the PATH
and created server.js as the first test
run
   ringo server.js // yes, it worked 

but when I tried to create project using
   ringo-admin create --google-appengine test01
or
   ringo-admin create test01/
none of these are work
it just gave me a
">>"

![Capture](https://f.cloud.github.com/assets/2391982/191397/b8407120-7f35-11e2-8c33-623fd1b31e96.PNG)

some kind of ringo console, i guess
but whatever I typed in, it returned me that "those are undefined"
I don't know what to do with this to create a appengine project.

Please someone help me? 
I want to use AppEngine with javascript using RingoJS

Thank you

**Comment by oberhamsi** [comment]
sounds like the symlinks were created as files in mingw32. I doub there's anything we can do about that.

A workaround could be to run the scripts with cygwin or git bash. We also provide batch files for windows development.
