### ISSUE TITLE
ignore .svn directory

### ISSUE THREAD

**Issue by bartvde** [ringo/ringojs#228]
is there a way to ignore a .svn directory in the packages folder?

buildjs:
     [java] Error configuring package FileRepository[/Users/bartvde/opengeo/git/mareano/externals/ringojs/packages/.svn/]: JavaException: java.io.FileNotFoundException: /Users/bartvde/opengeo/git/mareano/externals/ringojs/packages/.svn/package.json (No such file or directory)

**Comment by botic** [comment]
I cannot reproduce this error on my machine. How do you start ringo? Is there anyone else with this problem?
