### ISSUE TITLE
Promise.wait() blocks setTimeout

### ISSUE THREAD

**Issue by oravecz** [ringo/ringojs#229]
I wasn't sure what to type for the subject as this isn't quite a bug or an enhancement request. It's just a behavior that could be changed perhaps.

``` js
var {Deferred} = require( 'ringo/promise' );

var deferred = new Deferred();

setTimeout( function () {
    deferred.resolve( 'hello world' );
}, 1000 );

var value = deferred.promise.wait( 5000 );

print( 'Value: ' + value );
```

When executed, the above code prints out "Value: undefined" after a 5 second pause. I was expecting it to print out "Value: hello world" after a one second pause.

My expectation is that the deferred.wait() would be interrupted by the deferred.resolve() in the setTimeout handler. But instead deferred.wait() blocks the setTimeout countdown timer because it is also on the main event thread. 

The following code illustrates the affect I was hoping to achieve.

``` js
var {Deferred} = require( 'ringo/promise' );

var deferred = new Deferred();

function newTimeout( f, delay ) {
    new java.lang.Thread( new java.lang.Runnable({
        run: function() {
            java.lang.Thread.sleep(delay);
            f.call(this);
        }
    }) ).start();
}

newTimeout( function () {
    deferred.resolve( 'hello world' );
}, 1000 );

var value = deferred.promise.wait( 5000 );

print( 'Value: ' + value );
```

There would be issues with this naive replacement for setTimeout, particularly the fact that the concept of 'this' is changed. Calling new Timeout like this would solve that problem:

``` js
newTimeout( function () {
    deferred.resolve( 'hello world' );
}.bind(this), 1000 );
```

So, I'm not particularly suggesting an enhancement or pointing out a defect. There may be very good reasons why setTimeout _has_ to be run on the main event loop. 

The inclusion of Promise.wait() is a very nice option when blocking is required, so I am glad to have it available, even if it requires some additional knowledge regarding its use.

**Comment by botic** [comment]
I’m closing this issue because it has been inactive for a long time. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this / there is no interest in it.

Please reopen if you still encounter this issue with the current master version or there is a need to address this issue.
