### ISSUE TITLE
adding jars of packages to classpath

### ISSUE THREAD

**Issue by oberhamsi** [ringo/ringojs#234]
in a lot of packages i do this:

    // add all jar files to the classpath
    var dir = module.resolve("../jars/");
    fs.list(dir).forEach(function(file) {
      if (fs.extension(file) === ".jar") {
          addToClasspath(fs.join(dir, file));
      }
    });

since we already have the "jars" property in package.json, ringo might do this for me:

    "jars": [
        "jars/lucene-core-2.4.1.jar",
        "jars/lucene-analyzers-2.4.1.jar"
    ]

Is it a bad idea to autoload them? Any thoughts?

**Comment by botic** [comment]
#156 is related to this issue.
