### ISSUE TITLE
should dates.parse() throw exception on invalid date?

### ISSUE THREAD

**Issue by oberhamsi** [ringo/ringojs#247]
currently it returns `new Date('invalid')` but unless there's something special about an "invalid" date, i would rather get an exception and deal with that

**Comment by botic** [comment]
From the ES6 spec: *"Unrecognizable Strings or dates containing illegal element values in the format String shall cause Date.parse to return NaN."*

I would recommend to follow this approach.

**Comment by botic** [comment]
For further discussion see #294
