### ISSUE TITLE
move markdown and mustache into extra packages?

### ISSUE THREAD

**Issue by oberhamsi** [ringo/ringojs#249]
wondering why this is not in extra packages. both are only used in jsdoc so we would have to extract that too.

imo markdown is a vague target and our getLink() wasn't helping me with github wiki syntax. not flexible enough.

with mustache i'm not so sure. it's small and complete and maybe ringo should have a basic template solution in stdlib.. web focus and all.

**Comment by botic** [comment]
Candidates to be removed in Ringo 0.12:

* ringo/jsdoc
* ringo/parser
* ringo/mustache
* ringo/markdown

We could provide them in separate packages. The naming should indicate their origin, so something like `legacy-ringo-mustache` or `oldringo-mustache`.

**Comment by botic** [comment]
Another candidate for removal:

* ringo/daemon

The init script uses ringo/httpserver instead and it looks like the daemon module is a relict from the old times: https://github.com/ringo/ringojs/commit/f4d5f14848e37aa7df5b879a1f124da341fdad60 Applications using the init script should implement the methods `init`, `start`, `stop`, `destroy` on their own.

**Comment by oberhamsi** [comment]
-1 removing ringo/daemon.

we need the daemon interface whenever the app starts more then just a httpserver or something completely different :) e.g. websocket, ftpserver, other Workers,...

**Comment by botic** [comment]
Yep, that's true. I forgot that this is an integral part of the init script.

**Comment by botic** [comment]
@oberhamsi / @grob any ideas how this modules should be named on packages.ringojs.org? We should publish them to make the transition from 0.11 to 0.12 easy and smooth.

**Comment by oberhamsi** [comment]
probably ringo-markdown and ringo-mustache?

and ringo-jsdoc which contains the tool itself and the ringo/parser module.

**Comment by grob** [comment]
@oberhamsi: :+1:, but i'd put the parser into a separate module (ringo-jsparser), afais it doesn't have any jsdoc-specific code in it and it could be helpful for other tasks too.

**Comment by botic** [comment]
Markdown and Mustache are now available in the registry:

* http://packages.ringojs.org/packages/ringo-mustache
* http://packages.ringojs.org/packages/ringo-markdown

**Comment by botic** [comment]
Merged into master in 7c33f76d1c64104490eda5625dddebc706e2702a
