### ISSUE TITLE
ringo/term inserting " " (whitespace) after control sequence

### ISSUE THREAD

**Issue by oberhamsi** [ringo/ringojs#250]
Current behaviour of `term.write` is that it inserts `" "` (whitespace) after each
argument which is just an ANSI control sequence. e.g.:

    >> term.writeln("Hello", term.RED, "World");
    Hello World
    
I can see why this is convenient for simple output but it's very annoying when
outputting cursor movement sequences since those get offset by x+1.

Should we change this and break a lot of existing code? Or should we leave
it and just say that anything more then colors is out of scope for ringo/term?

I was able to work around ringo/term behaviour by wrapping `term.write` and concatenating all arguments into one string:

    >> term.writeln("Hello" + term.RED + "World");
    HelloWorld

**Comment by botic** [comment]
`term.write` follows the console convention. So I would not change this and use the workaround proposed by @oberhamsi

```
Philipps-MacBook-Pro:~ philipp$ node
> console.log("foo", "bar");
foo bar
```
