### ISSUE TITLE
Drop Java 5 support

### ISSUE THREAD

**Issue by botic** [ringo/ringojs#268]
The Java 5 options will be removed from future JDKs. So the upcoming 0.11 release should be the last with Java 5 support. After this we should remove the compiler flags to avoid future warnings and errors.

```
compile:
    [javac] Compiling 2 source files to /Users/philipp/Code/ringojs-master/build/classes
    [javac] warning: [options] source value 1.5 is obsolete and will be removed in a future release
    [javac] warning: [options] target value 1.5 is obsolete and will be removed in a future release
    [javac] warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
    [javac] 3 warnings
```

**Comment by botic** [comment]
A lot of NIO and file related stuff has been introduced in Java 7. So dropping Java 5 would bring us only some better compiler output, but does not help us for issues like #293 to drop also the JNI POSIX layer.

My proposal would be to require Java 7 as a minimum for Ringo 0.12 as the next release. What do you think, @grob / @oberhamsi / @kmfdm1 ?

**Comment by grob** [comment]
:+1:

**Comment by botic** [comment]
This needs further changes in the Debian build files, where Java 5 and 6 are minimum dependencies at the moment.
