### ISSUE TITLE
ringo/httpclient should have default timeouts

### ISSUE THREAD

**Issue by botic** [ringo/ringojs#281]
There is a common problem in applications using the http client: if the server hangs / does not reply, it will keep the connection open forever. The default connect and read timeouts are 0, so infinite. This is not a good behavior in my opinion and there should be reasonable defaults.

* 120000 (2 minutes) is used in node for `server.timeout`, so this could be the timeout
* 60000 (1 minute) is used in Apache Wink for the read timeout

Any other suggestions? This would prevent unexpected behavior if the server is not replying fast enough. If a developer *wants* to wait forever, he / she could still set both timeouts to 0.

**Comment by kmfdm1** [comment]
+1

Not returning is harder to debug than a timeout.
Am 03.02.2015 14:03 schrieb "Philipp Naderer" <notifications@github.com>:

**Comment by kmfdm1** [comment]
I'd say 1 minute schould be enough. As you said before: devs may change
this value anyhow and waiting for one minute to get a response is fairly
long already.
Am 03.02.2015 17:38 schrieb "Philipp Naderer" <notifications@github.com>:
