### ISSUE TITLE
Drop POSIX wrapper and switch to java.nio

### ISSUE THREAD

**Issue by botic** [ringo/ringojs#293]
Java 7 has a lot of POSIX-related stuff in the java.nio package. We could try to replace the jnr-posix layer with plain java.nio by using classes like [PosixFileAttributes](http://docs.oracle.com/javase/7/docs/api/java/nio/file/attribute/PosixFileAttributes.html). Using java.nio avoids any native calls via the JNI / jaffl interface.

This issue depends on #268

Update: candiates for the nio switch are the fs and file utils.

**Comment by botic** [comment]
Initial work started in the [293 branch](https://github.com/ringo/ringojs/tree/issues/293).

**Comment by botic** [comment]
Windows doesn't support POSIX file permissions. I see two approaches to this problem:

* ignore the mode if `defaultFS.supportedFileAttributeViews()` doesn't contain `posix`; just create the file / directory without any mode
* throw an exception / throw back the Java exception

If I look on other POSIX-based Windows code, I see a general preference for the first way.

**Comment by kmfdm1** [comment]
+1 for the first way

Philipp Naderer <notifications@github.com> schrieb am Mo., 20. Juli 2015
19:15:

**Comment by grob** [comment]
:+1: for option 1: throwing an exception would be way too harsh.

**Comment by botic** [comment]
I think https://github.com/ringo/ringojs/commit/c99bce63e7bc32f4431aaec5ce140a079ac24f06 shows how the new `fs` methods will look like. imho this is a better approach since we drop the custom POSIX stuff and rely on the JRE to do the right things for us like applying the current umask.

In the first run I dropped the `fs.Permissions` class. The implementation relied on POSIX and was not filesystem agnostic. Instead, I moved the POSIX stuff into a utility class `PosixPermissions` which knows all the details and converts between octal, symbolic and Java enum notation. See https://github.com/ringo/ringojs/commit/7a8ab5ed149215e4dc417e37be506cf4b1fc43e7 for utility class.

**Comment by grob** [comment]
one nitpick: you're throwing strings as errors in various methods in the utility class, which means there is no stack trace available, and thus makes debugging much harder. you could/should use

     throw new Error("message")

instead. other than that your changes look really good! :+1:

**Comment by botic** [comment]
Argggghhhh, too much client side stuff in the last months. Will fix it.

**Comment by botic** [comment]
I created a pull request: #307, so any discussion should happen in the PR.
