### ISSUE TITLE
sandbox support

### ISSUE THREAD

**Issue by oberhamsi** [ringo/ringojs#295]
to avoid duplicate work, i closed the PR https://github.com/ringo/ringojs/pull/150

but i'm keeping the link to code & text here:

https://github.com/mrdon/ringojs/commit/28b611672e8dfad8ae5c292c7e882335ada5d9a8

 * Sandbox mode shutters all Java classes out but key ones
 * Only a handful of modules ported so far
 * Jsgi works for me, though I did need to subclass servlet classes and let them in via the shutter
 * File upload likely broken as 'fs' module can't be done easily

**Comment by botic** [comment]
I will close this for now. If there is demand for a full sandbox support, we can rethink how this can be done in a more maintainable way.
