### ISSUE TITLE
documention about ringojs http://ringojs.org/documentation/commandline_tools/

### ISSUE THREAD

**Issue by guxima** [ringo/ringojs#297]
hi, this link is died !!
ringo/scheduler – scheduling invocation of functions (threads)

**Comment by botic** [comment]
Fixed in the [ringojs.org repo](https://github.com/ringo/ringojs.org) and published. Thank you for reporting!

**Comment by guxima** [comment]
hi, i can't find any description for scheduler in globals
should i user setInterval instead of it ?

**Comment by kmfdm1** [comment]
Hi. ringo scheduler is gone as far as i know.
There are only js-native functions like setTimeout, setInterval.

Have a look at https://github.com/kmfdm1/ringo-scheduler
Maybe this is what you want.

**Comment by guxima** [comment]
thanks~
