### ISSUE TITLE
how can i get the http params

### ISSUE THREAD

**Issue by guxima** [ringo/ringojs#300]
export.app = function(req){...}

req.pathInfo just specify path

if i need params send by GET or POST, should i use req.env.servletRequest ??

but it doesn't has anything when i debug

**Comment by grob** [comment]
please don't open issues for asking questions - there's a [ringojs google group](https://groups.google.com/forum/#!forum/ringojs) for that.

you should rarely need to utilize `req.env.servletRequest`. in most cases you can use the `params` middleware that's provided with stick. just enable it with

    app.configure(..., "params", ...)

and then you can access any query or post parameters using either `req.queryParams`, `req.postParams` or `req.params` (the latter contains the merged query and post parameters).

have a look at the [examples](https://github.com/ringo/stick/tree/master/examples)  or the [skeleton](https://github.com/ringo/stick/blob/master/examples/skeleton/actions.js#L6) of that come with stick.

**Comment by guxima** [comment]
thanks~
