### ISSUE TITLE
about server port

### ISSUE THREAD

**Issue by guxima** [ringo/ringojs#301]
i specify the port in config/jetty.xml，but it doesn't work untill i use the command ringo-web -p 
is this a bug ??

**Comment by kmfdm1** [comment]
I would suggest that the -p option only overwrites the settings from jetty.xml if this is a possibility.
Possible with a default to 8080 if nothing is defined.

**Comment by guxima** [comment]
so this is a bug?
the node about port is invalide??

**Comment by kmfdm1** [comment]
I haven't looked into the code, but if there is a node for specifying the port - and it is used correctly - it should be honored. I assume you checked with the jetty-documentation as reference.

**Comment by guxima** [comment]
i try it with ringo-web -R-d -j/user/me/path/jetty.xml and found the real problem in ringo/httpserver.js
the xmlconfig will always be empty，but jettyConfig.content is filled with file contents !!!!
could anyone have a try ??

	options = options || {};

    var jettyFile = options.jettyConfig || 'config/jetty.xml';
    var jettyConfig = getResource(jettyFile);
    if (!jettyConfig.exists()) {
        throw Error('Resource "' + jettyFile + '" not found');
    }
    var XmlConfiguration = org.eclipse.jetty.xml.XmlConfiguration;
    var JsgiServlet = org.ringojs.jsgi.JsgiServlet;
    jetty = new org.eclipse.jetty.server.Server();
    xmlconfig = new XmlConfiguration(jettyConfig.inputStream);

    // port config is done via properties
    var props = xmlconfig.getProperties();
    props.put('port', (options.port || 8080).toString());
    if (options.host) props.put('host', options.host);
    xmlconfig.configure(jetty);
