### ISSUE TITLE
how to reset var defined by module.singleton

### ISSUE THREAD

**Issue by guxima** [ringo/ringojs#302]
var sql = require('sql-ringojs-client');
var datasource = module.singleton('pooling-source', function () {
                    return sql.connect('jdbc:mysql://host:port/logview?autoReconnect=true', 'xx', 'yy');
                })
var connection = datasource.getConnection();

there also be an SQL exception even i config "autoReconnect"

the exception is connection has closed

**Comment by oberhamsi** [comment]
for questions and support use the mailinglist https://groups.google.com/forum/#!forum/ringojs
