### ISSUE TITLE
Windows-Console and unicode characters

### ISSUE THREAD

**Issue by kmfdm1** [ringo/ringojs#303]
I got a problem with the umlaut ü which pointed my nose on this problem.
Simply fire up ringo and type the letter ü into the console. This will show the questionmark for unknown character. öä are working tough.. strange behavior.

A quick search with google brought me to [this](http://stackoverflow.com/questions/24601930/ringojs-is-not-printing-unicode-characters) page where a user suggests to use node.js instead .. putting in effort to debug this problem but obviously there is no more energy to report it here.. makes me a little sad.

**Comment by botic** [comment]
I started to work on this issue in [issues/303](https://github.com/ringo/ringojs/tree/issues/303).

**Comment by botic** [comment]
The problem can be reduced to the direct write to system.out, which ignores the encoding of the console: https://github.com/ringo/ringojs/blob/master/modules/ringo/shell.js#L213

A possible solution might write into a temporary PrintStream buffering the output stream and after the write operation is complete sending it to system.out.

**Comment by botic** [comment]
I created a PR: #304
