### ISSUE TITLE
changeWorkingDirectory() is not reliable

### ISSUE THREAD

**Issue by botic** [ringo/ringojs#305]
The working directory is always related to a process, in our case to the underlying JVM process of the current Ringo instance. Providing a method `fs.changeWorkingDirectory(dir)` is misleading: If a user calls this method, this has no effect if any Java IO or NIO methods are called directly. There is also [a workaround](https://github.com/ringo/ringojs/blob/master/modules/fs.js#L1260) needed to make this work in Ringo.

I would suggest to drop `fs.changeWorkingDirectory(dir)` without a replacement.

**Comment by kmfdm1** [comment]
Hi.

I'd suggest to raise an error stating that this fs-function is not
supported. This is a more explicit hint for one expecting it because it is
included in common js.

Best wishes,
Manfred
Am 21.10.2015 3:42 nachm. schrieb "Philipp Naderer" <
notifications@github.com>:

**Comment by grob** [comment]
+1 for deprecating this method (plus logging a warning), and dropping it with the next major release (1.0, hint hint :). dropping it immediately could break existing applications, which shouldn't happen in a minor release (even if it's in the 0.x range, which imho ringojs should leave as fast as possible - it's *really* stable).

**Comment by kmfdm1** [comment]
Desperately waiting for 1.0 😀

Robert Gaggl <notifications@github.com> schrieb am Mi., 21. Okt. 2015 20:19:

**Comment by botic** [comment]
I adapted JSDoc for Ringo to display deprecation messages:

![deprecation](https://cloud.githubusercontent.com/assets/193023/10664968/e6158318-78c7-11e5-8c50-90e1c5cbb0a8.png)

**Comment by botic** [comment]
Fixed in https://github.com/ringo/ringojs/commit/1643bb09516c394c77fafa2105efd3003f3a9457
