### ISSUE TITLE
Deprecate ringo/httpclient and move it into a separate package

### ISSUE THREAD

**Issue by botic** [ringo/ringojs#310]
The current http client has at least drawbacks:
- callbacks suggests that it operates async, but in reality it's blocking and sync
- `complete` callback is triggered even if the underlying client throws an exception with e.g. 'timeout' as content
- the current handling of timeouts is not very consistent with other clients

We can fix them as far as possible for 0.12, deprecate the client with 0.12 and remove it after the release. To ensure that existing code will continue to work, we can move it into [ringo/legacy-modules](https://github.com/ringo/legacy-modules).

For 1.0 we will provide a standalone client as a separate package available via rp / http://packages.ringojs.org

This issue would solve #267 and should be integrated into the branch [issues/267](https://github.com/ringo/ringojs/tree/issues/267).

**Comment by oberhamsi** [comment]
i'm using the httpclient a lot but never with callbacks. If only the callback options are removed but the rest of the API stays the same (request methods + exchange object), then it shouldn't break my code (i hope...).

i suggest we deprecate the callback argument options in 0.12 and remove them in the next release. 

i'm not sure we need a legacy module - the callback options are legacy from the multithreaded httpclient we deprecated before that. The callbacks make no sense in the current httpclient (as you mentioned).

**Comment by botic** [comment]
Note that there is also a PR from @kmfdm1 on the httpclient: https://github.com/ringo/ringojs/pull/276/files

**Comment by kmfdm1** [comment]
Oh. Don't even remember this one.
Http client as extra package in 1.0 sounds good. No need to update ringojs
when there are problems in packages which aren't essential to the core.

Philipp Naderer <notifications@github.com> schrieb am Sa., 21. Nov. 2015
09:58:

**Comment by botic** [comment]
I think the `ringo/httpclient`should stay as it is in the current master and also in a potential 1.x line. The client itself could be obsolete after a Java 9 release in 2017 and until then I would continue as it is.

**Comment by botic** [comment]
The new JDK HTTP client will not ship before JDK 10.

**Comment by botic** [comment]
We will keep the existing client for 2.0 and keep the functionality in Ringo.
