### ISSUE TITLE
App Engine support broken: java.nio.files.* classes are not on the whitelist

### ISSUE THREAD

**Issue by botic** [ringo/ringojs#313]
Since `java.nio.files.*` is not available on App Engine, the current master doesn't work on it.

**Comment by botic** [comment]
After some investigation: The fs module has to be replaced by one using only `java.io.*`. Is there an easy way to implement this? How could a "gae-fs" module be hidden from the rest of the world, so that it will be only in place if the application runs in an App Engine environment? Something like a `ringo/internal/gae-fs`, which is a little bit like `sun.misc.Unsafe` 😉And fs checks if it's running in a App Engine instance and if yes, it re-assigns all GAE-compatible methods with the `ringo/internal/gae-fs` ones.

```
fs.read --> ringo/internal/gae-fs.read
fs.open --> ringo/internal/gae-fs.open
...
```

**Comment by grob** [comment]
fwiw, definitely :+1: to the latter. i personally don't like the idea of gae deficiencies defining the limits to improvements in ringojs, and i certainly wouldn't want to see any hacks in ringojs to cope with them. switching fs module to java.nio for sure is a big improvement, so if gae can't deal with it - so be it (and wait for them to fix it).

we could however add the previous `java.io`-based fs module into our infamous legacy module, but i'm hesitant ;-)

**Comment by oberhamsi** [comment]
+1 dropping gae for now. nio in fs is a great improvement and i wouldn't want to hassle ringo with gae specific workarounds.

**Comment by botic** [comment]
Dropping GAE seems to be the only solution. I hope Google finally fixes the sandboxed runtime and brings Java 8 and NIO to it. But my guess is that they move ahead with containers and Managed VM runtimes, which is not that cool from the autoscaling perspective …
