### ISSUE TITLE
release to maven

### ISSUE THREAD

**Issue by oberhamsi** [ringo/ringojs#315]
we need an official release on maven

others do it http://search.maven.org/#artifactdetails|io.ejs|ringojs|0.11.0|jar

**Comment by botic** [comment]
This would allow us an easier integration into various cloud platforms, since Ringo would just be a dependency.

**Comment by tangrui** [comment]
Will Ringo change build infrastructure from Ivy to Maven?

**Comment by botic** [comment]
I will work to bring Ringo 1.1.0 + into central. See https://issues.sonatype.org/browse/OSSRH-28297

**Comment by botic** [comment]
Todo: License information missing, SCM URL missing, Developer information missing
