### ISSUE TITLE
Drop Java 7 support

### ISSUE THREAD

**Issue by botic** [ringo/ringojs#321]
In 99e546f9a295279fcc3f9ac00790e0bf0e735e72 @grob updated to Jetty 9.3, which requires Java 8. Therefore the Codeship tests fail for OpenJDK 7. My vote would be for dropping Java 7, since it's also end of (public) support by Oracle.

**Comment by botic** [comment]
I removed the JDK 7 tests from Codeship, since the current master requires JDK 8.

**Comment by oberhamsi** [comment]
i'm not super happy about this but the jetty guys seem dedicated to java8:

> Jetty-9.3 is built and targeted for Java 8.  This change was prompted by the SNI extension reliance on a Java 8 API and the HTTP2 specification need for TLS ciphers that are only available in Java 8.  It is possible to build Jetty-9.3 for Java 7 and we were considering releasing it as such with a few configuration tricks to enable the few classes that require java 8, however...

https://webtide.com/jetty-9-3-features/

**Comment by grob** [comment]
I' don't see a big problem with dropping java 7 support, but if it turns out to be one i'm fine with reverting this change.

**Comment by oberhamsi** [comment]
oh, i forgot: +1 for moving with jetty and dropping java7. we wouldn't want to stumble into 1.0 with legacy dependenices ;)

@botic thx for fixing the tests

**Comment by botic** [comment]
Since Jetty has no alternative for the ciphers in Java 7 and HTTP/2 should be supported by every modern HTTP server in the near future, it's just a step we have to follow at least with 1.0. Also the effective EOL for non-paying customers is a very valid argument. So we will jump directly from dropping Java 5 support to Java 8. And: JDK 9 is just around the corner for fall 2016.
