### ISSUE TITLE
fs.canonical returns a java.nio.file.Path instance

### ISSUE THREAD

**Issue by grob** [ringo/ringojs#322]
@botic According to the documentation `canonical()` returns a string, but [it returns an instance of `java.nio.file.Path`](https://github.com/ringo/ringojs/blob/master/modules/fs.js#L956). Afais all other methods return strings, but otoh this method is used internally quite often, so it would probably best to split it into an internal method an one that is exported.

**Comment by botic** [comment]
Merci! All `canonical()` calls in fs treated the return value like a string, so fixing this was easy.

**Comment by grob** [comment]
thanks for the fix!
