### ISSUE TITLE
module.resolve  do not return a resolved path 

### ISSUE THREAD

**Issue by a564941464** [ringo/ringojs#327]
when deploy the app in a java sevlet container

**Comment by botic** [comment]
Which container are you using and are you on master or on 0.11?

**Comment by a564941464** [comment]
0.11. and the container is apache-tomcat-7.0.68-windows-x64. module.resolve do not return a resolved path:  /WEB-INF/.....

**Comment by botic** [comment]
What is your exact `module.resolve()` call? I think since a WebappRepository doesn't have a parent, resolving `..` fails. You can only resolve inside the current directory at the moment.

**Comment by a564941464** [comment]
What is your exact module.resolve() call? The module's path.

**Comment by botic** [comment]
```javascript
exports.index = function (req) {

  // works
  module.resolve("./public/stylesheets/page.css");

  // doesn't work since resolving cannot escape the current directory
  // inside a WAR / Java Web application
  module.resolve("../web.xml")
};
```

If you want to deploy inside a JEE Servlet container, then you should use the "native" servlet and its corresponding servlet context directly:

```
exports.index = function (req) {
  const currentJsgiServlet = req.env.servlet;

  // returns a javax.servlet.ServletContext
  const currentServletContext = currentJsgiServlet.getServletContext();
  
  // returns an absolute path to the resource
  const realPath = currentServletContext.getRealPath("/WEB-INF/web.xml"));
}
```

**Comment by botic** [comment]
* If you are inside a servlet container and want to access resources from `/WEB-INF` of your current application, you should use the servlet context to obtain them. Since the container provides your application its context, this is the only reliable way.
* I will add an additional property `servletContext` to the JSGI request for easier access
