### ISSUE TITLE
ringo file.js > output.txt and console.log

### ISSUE THREAD

**Issue by cancerberoSgx** [ringo/ringojs#335]
It seems strange to me that a command like : 

  ringo foo.js

dumps the outputs of console.log() in stderr instead of stdout . That's what other JavaScript implementations like node, v7, etc do and what I would spec of console.log in the terminal. 

In other words I have to do : 

  ringo output.js 2> output.txt

instead of just ringo output.js > output.js

great project !!

**Comment by botic** [comment]
Thx for your feedback. We are pretty close to release RingoJS 0.12 where this will be fixed: b1dc348aa37c25c676b10e0cbe473516e243b81c

**Comment by cancerberoSgx** [comment]
thanks! yes I just used my OS package manager to install it - not from the source, sorry and thanks again
