### ISSUE TITLE
TLS / SSL on ringojs.org

### ISSUE THREAD

**Issue by botic** [ringo/ringojs#338]
We should provide a letsencrypt-based TLS setup on ringojs.org

**Comment by sclee15** [comment]
I also looking forward this too.
I really want to use plain ringo not servlet.
but i failed to manage to enable https without servlet.

**Comment by botic** [comment]
I think I will update RingoJS to https://github.com/grob/httpserver (which I hope will replace the current HTTP server in 2.0). The configuration is easier and we need some real world tests. ringojs.org looks like a good place for that.

The other way is to use Jetty's `jetty.xml` and configure the keystore stuff there:
http://www.eclipse.org/jetty/documentation/9.3.x/configuring-ssl.html

**Comment by botic** [comment]
* Releases will be served by simplesite and not by Apache in the future. For this all release files have to be uploaded into [ringojs.org under `/releases/MAJOR.MINOR.PATCH`](https://github.com/ringo/ringojs.org/tree/master/releases/1.0.0-RC1). This makes releases and checksums better trackable, even if it needs some binaries inside an repository. But imho for this case this is okay. See https://github.com/ringo/ringojs.org/commit/34969bc9cbe1fa9c6eae13a000d90d84805dc469 and https://github.com/ringo/simplesite/commit/11fda436f5439227d9fa755eb7c81cc7065e1afd and https://github.com/ringo/simplesite/commit/222c38e9208182688c3e9756a709d9f68dcf05bd
* We use https://letsencrypt.org as provider for the certificate.
* The old Apache-based sites will redirect everything from the ringojs.org content to the https site, but not the old `http://ringojs.org/downloads/*` links. This would break older installations via brew and other tools.
