### ISSUE TITLE
Add loadJars() to load a directory of JARs

### ISSUE THREAD

**Issue by botic** [ringo/ringojs#350]
A lot of applications have code like the following to load all JARs from a given directory into the class path. Should we provide it out of the box and if yes, in what module?

``` javascript
/**
 * Loads all .jar files placed in the `jars` directory of SqlStore
 */
var loadJars = exports.loadJars = function() {
    // add all jar files in jars directory to classpath
    var dir = module.resolve("../../../jars/");
    var repo = getRepository(dir);
    var list = repo.getResources().filter(function(r) {
        return strings.endsWith(r.name, ".jar");
    });
    list.forEach(function(file) {
        addToClasspath(file);
    });
};
```

**Comment by botic** [comment]
Not 100% perfect, but it could be part of `ringo/utils/files`

**Comment by kmfdm1** [comment]
Why not engine? It is more of an engine-extending functionality than a file-reading/manipulating one..

**Comment by botic** [comment]
Prior art would be global. But is this still a good thing, @grob / @oberhamsi?
https://ringojs.org/api/1.2.1/globals/#addToClasspath

**Comment by botic** [comment]
So I see three options:

1. adding a `addJarsToClasspath(dir)` to the global object. But this is broken by design, since we should never ever add anything to global again.
2. add `addJarsToClasspath(dir)` in the engine module, like Manfred proposed. But then we should also add the standard `addToClasspath(path)` to the engine module, which would be a non-global alternative to `addToClasspath()`. The global variant would stay as legacy code, the engine alternatives would be the way to go.
3. Drop this issue and keep copying this snipped.

**Comment by botic** [comment]
Pull request: #425
