### ISSUE TITLE
droping support for java 1.7...

### ISSUE THREAD

**Issue by mcarbonneaux** [ringo/ringojs#352]
ringojs are very usefull to developpe api agent!
and is very usefull to have support for java 7 beceause not all old plateform have java 8!
on my environement i've many machine on many differente plateforme... aix (5.3 to 7.x), solaris(8 to 10), hp-ux (11.23 to 11.31, ppa and ia64), linux x86, windows ...
no all of this plateform support java 8... somme support only java 6...
rhino support java 6+...
why limiting to java 8 only ?
what the big effort to support java 6/8 ?
to my mind i think using jetty 9.3 in place of jetty 8 (java 6)/9.2 (java 7) limit support to java 8...

**Comment by botic** [comment]
Have you ran into a specific exception / problem or is this a question only on the general support of Java 7?

**Comment by oberhamsi** [comment]
@mcarbonneaux you are right, jetty forced us to switch to java 8. the httpserver is such an integral part of ringo that we want it to be up to date. @botic do you know which release was the last to support java 7?

**Comment by botic** [comment]
Most stuff will still work under Java 7. Only the fs module and Jetty require Java 8. App Engine is still working and there Java 7 and Jetty 6 the standard. That's why I asked if you ran into a specific error.

**Comment by mcarbonneaux** [comment]
if y install ringojs with jetty 7 and jvm 6 they can work if i not use fs module ?

**Comment by botic** [comment]
Yes, since the missing classes are accessed on demand. That's why RingoJS still works on App Engine, where the `fs` module has no role in the standard runtime based on Jetty 6 & Java 7.

**Comment by botic** [comment]
A good example where I worked around this is in the following commit:
https://github.com/ringo/ringojs/commit/a635dec1d24bb29490a88ec7e30f0c1fdc49199c

**Comment by botic** [comment]
The old POSIX-based fs module is published in rp if you need it for backwards compatibility: http://packages.ringojs.org/packages/posix-fs
