### ISSUE TITLE
is module .resolve borken for a absolute path?

### ISSUE THREAD

**Issue by sclee15** [ringo/ringojs#356]
hello. 
ringojs is fun to use thank you.
should module .resolve("/etc") gives me /etc?
instead it gives me my current path/etc
i cloned github master and
just called ./bin/ringo main.js

thank you

**Comment by botic** [comment]
The reason behind this is somewhere between release 0.7 and 0.8 …

RingoJS 0.6

```
Philipps-MacBook-Pro:ringojs-0.6.0 philipp$ ./bin/ringo
>> module.resolve("/etc");
/etc
```

RingoJS 0.7
```
Philipps-MacBook-Pro:ringojs-0.7.0 philipp$ ./bin/ringo
>> module.resolve("/etc")
etc
```

RingoJS 0.8
```
Philipps-MacBook-Pro:ringojs-0.8.0 philipp$ ./bin/ringo
>> module.resolve("/etc");
'/Users/philipp/Downloads/ringojs-0.8.0/etc'
```

**Comment by sclee15** [comment]
Thank you for looking into this
The desired answer is /etc
So the issue started at 0.7 i think

**Comment by botic** [comment]
A possible idea could be that repositories are the root of all resources. If you use `module.resolve('/etc/foo')` this looks at the root of the repository, not the file system itself. We have different types of repositories: arbitrary file system repos, web application repositories (compare their concept to WARs) and JAR repositories. It could be that the idea behind the current implementation is something comparable to a weak chroot.

**Comment by botic** [comment]
After a deeper look: `module.resource()` was the original idea behind `module.resolve()` for looking up resources relative to module location. See #66 for the issue. A path returned by `resolve()` should always be relative to the current modules location and never be absolute. It would also make no sense to resolve an absolute path, since it's already absolute. So I guess we should fix the documentation asap.

**Comment by botic** [comment]
Documentation now provides an example:
http://ringojs.org/api/master/globals/#module.resolve

**Comment by sclee15** [comment]
@botic thank you for the investigation.

i used module.resolve stick to old documentation.
if api choose to stay on only on relative path,
i should find another way to resolve path then.

thank you.

**Comment by botic** [comment]
Can you give me the link to the old docs?
