### ISSUE TITLE
Replace ringo/httpserver with httpserver package

### ISSUE THREAD

**Issue by botic** [ringo/ringojs#358]
Move the `httpserver` module by @grob into Ringo and replace `ringo/httpserver`.

**Comment by botic** [comment]
This should also fix #207

**Comment by oberhamsi** [comment]
i figured out a way how to merge httpserver into ringo without losing history. basically grob's httpserver is imported as a branch in ringo. in that branch i move around the files so they fit ringo's structure, then the httpserver branch is merged into master.

in ringojs master:

    git remote add httpserver-remote ../httpserver/
    git fetch httpserver-remote
    git checkout -b grob-httpserver httpserver-remote/master
    mkdir -p modules/ringo/httpserver
    ## move lib into modules
    git mv lib/*js modules/ringo/httpserver/
    git mv lib/context modules/ringo/httpserver/
    ## main.js -> index.js so we can do require('ringo/httpserver')
    git mv modules/ringo/httpserver/main.js modules/ringo/httpserver/index.js
    ## rename examples
    git mv examples/app.js examples/httpserver-app.js
    git mv examples/default.js examples/httpserver-default.js
    git mv examples/fluent.js examples/httpserver-fluent.js
    git mv examples/jettyxml.js examples/httpserver-jettyxml.js

    ## remove obsolete
    git rm LICENSE
    git rm README.md
    git rm package.json
    git rm .gitignore

    # back to master and merge
    git checkout master
    git merge --allow-unrelated-histories grob-httpserver

after that, we have to fix the examples (trivial)

**Comment by botic** [comment]
Great news! I want to see it in a 2.0 and this makes it much easier to integrate it into the main line of Ringo.

**Comment by botic** [comment]
Should we merge it into master for the 2.0 release?

**Comment by grob** [comment]
:+1: for moving the old http server module into a separate package and merging.

**Comment by botic** [comment]
Merged in 3bea8a2d6a5bd2d5acd4af8545b97970c5b7ec29

**Comment by botic** [comment]
The old httpserver module has been published: http://packages.ringojs.org/packages/ringo-httpserver

**Comment by botic** [comment]
Shiped.
