### ISSUE TITLE
Update logging to newest releases of Log4J and SLF4J

### ISSUE THREAD

**Issue by botic** [ringo/ringojs#365]
The current versions are quite old. This will break existing configurations!

**Comment by botic** [comment]
I ran into problems with Elasticsearch's new REST client which depends on Log4J 2.x and breaks with the current logging config. Since I see a lot of other projects updating to 2.x, this might be the best option for the upcoming 2.x series.

**Comment by oberhamsi** [comment]
slf4j upgrade is already in master. log4j2 has different properties format so i prepared it in this branch:

https://github.com/ringo/ringojs/tree/log4j2

i was thinking of dropping slf4j since log4j can now act as a facade too but jetty looks for slf4j and it's not much trouble to keep it.

**Comment by botic** [comment]
Log4j2 user guide: https://logging.apache.org/log4j/2.x/log4j-users-guide.pdf

**Comment by grob** [comment]
Wouldn't this be a candidate for 3.0?

**Comment by grob** [comment]
See #407

**Comment by botic** [comment]
Fixed / integrated into master with e41cbe274aafaed56e466d6db9122319001208d7
