### ISSUE TITLE
web application module executed twice??

### ISSUE THREAD

**Issue by guxima** [ringo/ringojs#369]
i used stick in my project as follows
`require('ringo/httpserver').main(module.resolve('app.js'))`
and i found 'app.js' will be ran twice!!
first times at "ringo/httpservers.js",line 481
` server = new Server(options);
var app = require(options.appModule); // app.js invoked by "require"`
second times as 'jsgi/connector.js', line 28
`var module = require(moduleId);
        app = module[functionObj]; // app.js invoked by "require" again` 

so, what's the problem?

**Comment by grob** [comment]
that's how ringo's httpserver resp. the jsgi connector work: the httpserver requires your app module during `init()`, and the jsgi connector requires it for every thread starting.

**Comment by guxima** [comment]
why the module didn't cached?
what i see as 
> Modules are cached after they are loaded for the first time. Ringo tries to resolve module ids to a canonical path in order to not load the same module twice, but it is possible under rare circumstances that this fails and a module is loaded twice.

**Comment by guxima** [comment]
well, I know what's wrong with my project
I should set my spawn into singleton or put it into main.js not app.js
Is that right?

**Comment by botic** [comment]
You might put the functionality into a separate function and invoke it via a worker:

```
const myWorker = new Worker("./computational-expensive-module");

exports.app = function() {
   // parallel stuff 
   myWorker.postMessage(...);
}
```

https://ringojs.org/documentation/workers/

**Comment by guxima** [comment]
That's great
Thks very much
