### ISSUE TITLE
Classpath Only Solution

### ISSUE THREAD

**Issue by mfreeman-xtivia** [ringo/ringojs#370]
Any idea if its possible to use RingoJS in a way where everything is loaded/discovered from the classpath?

I am thinking I would  like to use the features that RingoJS offers, especially the multi-threading, but my application needs to live inside an OSGi environment where traditional access to the filesystem, either directly or using things like getRealPath() are not going to work...

**Comment by botic** [comment]
It depends. If you use modules relying on `fs`, than you will still face problems. Otherwise I see nothing which should prevent Ringo from launching only with classpath-based modules.

[Ringo's launcher](https://github.com/ringo/ringojs/blob/master/src/org/ringojs/tools/launcher/Main.java) is the basis behind `run.jar`, which contains only a stub to bootstrap the core modules and the runtime itself. You can create a custom `RingoConfig` ([source](https://github.com/ringo/ringojs/blob/master/src/org/ringojs/engine/RingoConfig.java), [usage](https://github.com/ringo/ringojs/blob/master/src/org/ringojs/tools/RingoRunner.java)) without anything from the file system and only load modules from the classpath itself.

**Comment by mfreeman-xtivia** [comment]
So would I need to implement a new 'ClasspathRepository' and then specify that in the configuration? is that the essence of the approach you are recommending?

**Comment by botic** [comment]
One very easy way would be to set the `ringo.home` env var to a jar, e.g. `ringo -Dringo.home=./core/ringo-modules.jar` to enforce loading modules directly out of the jar ([source](https://github.com/ringo/ringojs/blob/master/src/org/ringojs/tools/RingoRunner.java#L113)).

**Comment by mfreeman-xtivia** [comment]
Thank you--unfortunately my potential use case is geared more toward operating inside a servlet environment so I am not sure how well/easy I can adapt some of the more CLI/standalone oriented examples to my particular problem.

**Comment by botic** [comment]
Ringo provides a JSGI servlet which can be configured to use a custom `ringo.home` too. Some general documentation: https://ringojs.org/documentation/jsgi_servlet_lifecycle/

You can set `ringo-home` and `module-path` to a custom jar with the `<init-param>` in your `web.xml` ([source](https://github.com/ringo/ringojs/blob/master/src/org/ringojs/jsgi/JsgiServlet.java#L71)).

**Comment by mfreeman-xtivia** [comment]
So I am following you, but for the sake of conversation, if were to execute in a servlet environment, which no real knowledge of the file system per se, and wanted to generalize my servlet code so that it doesn't know about any specific JAR locations (i.e. knows only that modules are in the classpath somewhere), would it be as simple as implementing a ClasspathRespository and tweaking the configuration to use it?

**Comment by botic** [comment]
The JSGI servlet will use the container-provided servlet context to load all resources. So you have to provide the modules in the `WEB-INF` [[1](https://github.com/ringo/ringojs/blob/master/src/org/ringojs/jsgi/JsgiServlet.java#L82)] [[2](https://github.com/ringo/ringojs/blob/master/src/org/ringojs/repository/WebappResource.java#L57)] [[3](https://github.com/ringo/ringojs/blob/master/src/org/ringojs/repository/WebappRepository.java#L73)]. This is how RingoJS runs on top of Google App Engine standard environment:  Everything is bundled into a WAR / web application directory. You have no access to the filesystem on App Engine, so this could match your use case quite well.

**Comment by botic** [comment]
Btw. stachelhaut is such an application running on App Engine: https://github.com/botic/stachelhaut

**Comment by mfreeman-xtivia** [comment]
Almost :-(

I am targeting an OSGi container environment which doesn't really do file-system based access to anything (ie anything based on java.io.File). Its the kind of situation where things like getRealPath() dont work. Anything that is classpath-based, and uses classloader oriented io like getResourceAsStream etc will work just fine. 

So typically I use classloader based solutions to read files from my archive

**Comment by botic** [comment]
Maybe this can help, I never had such a scenario. https://ringojs.org/documentation/java_integration/

**Comment by mfreeman-xtivia** [comment]
I understand--but I guess I am back to my basic question...

To what degree is RingoJS married to the concept of Files as modules? put another way could I implement a repository that only has classloaders, getResourceAsStreams, etc at its disposal for doing all module lookup and  I/O operations?

**Comment by botic** [comment]
Ringo / Rhino compile JavaScript sources into classes / bytecode on the fly. So there must be some textual representation of the script source. That's why a lot of places use streams and fs-based operations. Maybe the problem is not Ringo itself, but the JavaScript nature?

**Comment by botic** [comment]
I will close this due long inactivity and the _wontfix_ status.
