### ISSUE TITLE
Add two new functions to JSGI response module

### ISSUE THREAD

**Issue by botic** [ringo/ringojs#371]
- `setHeaders()` like `addHeaders()`, but with an overriding behaviour
- `setContentType()` to set the mime type of a response

Both will help to keep the API fluent.

**Comment by botic** [comment]
@oberhamsi @grob What do you think? Anything else missing from your pov? You worked on a lot of API stuff and there this two functions might help a lot.

**Comment by grob** [comment]
both make sense, so :+1:
