### ISSUE TITLE
`files.createTempFile` creates files with restrictive permissions

### ISSUE THREAD

**Issue by grob** [ringo/ringojs#379]
[`files.createTempFile`](https://github.com/ringo/ringojs/blob/master/modules/ringo/utils/files.js#L104) doesn't allow to define the permissions of the created file (although the utilized `java.nio.file.Files` method does), and as a result on linux/ubuntu the created files are read/writable only for the file owner. From the java docs:

> When no file attributes are specified, then the resulting file may have more restrictive access permissions to files created by the File.createTempFile(String,String,File) method.

`files.createTempFile` should imho use a more relaxed default permission (i.e. "rw-r--r--") and/or allow passing the permissions

**Comment by botic** [comment]
Scheduled for 1.2, merci!

**Comment by kmfdm1** [comment]
Please don't use more relaxed defaults. You never know what may be stored in those files and i think the aproach of java, that those files have more restricted permissions set, is based on the asumption that there may be stored sensitive data. We should also follow this philosophy of being on the save-side and only implement the possibility to suply the permissions to be used.

**Comment by botic** [comment]
You can provide additional permissions starting with the 1.2 release.

**Comment by grob** [comment]
great, thanks for fixing!
