### ISSUE TITLE
JDK9: -Xbootclasspath/p is no longer a supported

### ISSUE THREAD

**Issue by botic** [ringo/ringojs#381]
```
Philipps-MacBook-Pro:~ philipp$ ringo -v
-Xbootclasspath/p is no longer a supported option.
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

**Comment by jgabios** [comment]
I changed -Xbootclasspath/p with -Xbootclasspath/a and it went passed. However I am stuck with: "java.lang.RuntimeException: No Context associated with current Thread"

**Comment by botic** [comment]
> The --patch-module option replaces the -Xbootclasspath:/p option, which has been removed (see below).
> The --patch-module option is intended only for testing and debugging. Its use in production settings is strongly discouraged.

What does `Xbootclasspath` do?

> Sets the search path for bootstrap classes and resources. The default is to search for bootstrap classes and resources in the internal VM directories and .jar files. 

The append and normal mode are still available, only the prepend has been removed due the new modular approach with Jigsaw.

So I will follow @jgabios approach to use the append option instead of prepend in Ringo 1.2.1. Please note that we will still need to verify that everything works with JDK 9+ and keep an eye on Jetty & Rhino.

See adb516aa86e90cb6368fc63cbd3fdd30914894c4

**Comment by grob** [comment]
Correct me if i'm wrong, but the jar that is prepended by `-Xbootclasspath:/p` doesn't exist anymore - it's supposed to be rhino's `js.jar`, but iirc this changed when the build env switched to ivy. i think this option is a leftover from a long time ago and can be safely removed.

**Comment by botic** [comment]
My problem is: I cannot judge this since there is no link to the OpenJDK bug it is intending to fix. My first thought was that this could also target some (now legacy?) setups. At least OpenJDK 8 works as expected.
