### ISSUE TITLE
ringo shell no longer starts

### ISSUE THREAD

**Issue by oberhamsi** [ringo/ringojs#383]
i'm using latest release, all the unit tests run through but if i try to start the shell i get:

     java.lang.RuntimeException: No Context associated with current Thread

**Comment by oberhamsi** [comment]
it's the rhino update in 40b986da0a66bd05994f6d99295a2a9785202549

**Comment by botic** [comment]
I'll release a 1.2.1 without the Rhino update asap and we will look into the issue next week.

**Comment by botic** [comment]
Release plan: Ringo 1.2.1 with the two bugfixes on late Monday (CET), so please take a look at the current master early next week.

**Comment by grob** [comment]
Changing the order of [ModuleScope.java#L42](https://github.com/ringo/ringojs/blob/master/src/org/ringojs/engine/ModuleScope.java#L42) and [ModuleScope.java#L44](https://github.com/ringo/ringojs/blob/master/src/org/ringojs/engine/ModuleScope.java#L44) seems to fix that, although i'm not sure about unwanted side-effects.

bisecting rhino lead to [171f38](https://github.com/mozilla/rhino/commit/171f38838caebbb42ab2040eefc09024989d10c5) as the commit that introduced this error, but this happend on 01.09.2015?

**Comment by botic** [comment]
I would suggest to release 1.2.1 tomorrow with the current master and the boot classpath fix and Rhino 1.7.7.1. After that we can loop at the scopes in master. Or any other suggestions how to continue the release?

**Comment by botic** [comment]
Fixed with the release of 1.2.1

**Comment by botic** [comment]
See acbdb4138972f8f4b6061dad55cd357222bda4c2 which implements @grob's fix for the latest Rhino.
