### ISSUE TITLE
fs-module incompatibility with windowsOS

### ISSUE THREAD

**Issue by kmfdm1** [ringo/ringojs#389]
Unfortunately posix-filepermissions arn't supported by the windows-fs.

This causes for example "ringo-admin install" of ringojs 1.2.1 to fail with an exception.

    Wrapped java.lang.UnsupportedOperationException
            at fs.js:1100 (changePermissions)
            at C:\work\ringoJS\ringojs-1.2.1\tools\admin\install.js:86 (installPackage)
            at C:\work\ringoJS\ringojs-1.2.1\tools\admin\install.js:156 (main)
            at C:\work\ringoJS\ringojs-1.2.1\tools\admin\main.js:14 (main)
            at C:\work\ringoJS\ringojs-1.2.1\tools\admin\main.js:30

@grob  fixed it already for the install-script in ringjs's master-branch, but we should deceide how to handle this issue at it's root in the fs-module.

Either add a compatibility-layer or add a check utility to let the developers handle this issue on their own + mentioning the incompatibility within the documentation for fs.

**Comment by oberhamsi** [comment]
maybe expose a `supportsPosix`. it's what @botic does in the unit tests https://github.com/ringo/ringojs/blob/b0309f96d81380918c9bd9ecc19e42a001d21cd4/test/file/test-fs-permissions.js#L12

**Comment by botic** [comment]
Fixed in c31e9b4ed44c0fa606e0452ea1643ea9b66a442e ➡️ discussion in #390
