### ISSUE TITLE
Refactoring ringo using intellij to automagically convert the codebase to kotlin

### ISSUE THREAD

**Issue by machinshin** [ringo/ringojs#401]
@hns  , et.al.

What do you all think of the idea? I think long large reason that this project isn't getting the open source help it deserves is because Java is ... no longer anyone's favorite language. What about it? I know that I for one would want to contribute more if we were using Kotlin ;)

**Comment by botic** [comment]
Hannes is no longer active in the project.

I don't see any chance to switch the core's language to Kotlin. Where should the resources for this step come from? All current involved people are fluent in Java and I don't see any huge win.

Please also note what I wrote down for last year, which is still true: Changing a lot of the core or touching the module loader system is non-goal. https://github.com/ringo/ringojs/wiki/Goals-for-2018

**Comment by machinshin** [comment]
@botic thank you for the update on the status of this project!

**Comment by machinshin** [comment]
in fact, to anyone who happens to come across this thread in the future, if you want a javascript/node-js interface on the JVM that gives js access to the JDK check out GraalVM.
