### ISSUE TITLE
binary module modifies String.prototype

### ISSUE THREAD

**Issue by grob** [ringo/ringojs#409]
During attempts to modernize/es6ify the default modules, i came around this: the ```binary``` module modifies ```String.prototype``` by adding the methods ```toByteArray``` and ```toByteString```. I certainly see the convenience, nevertheless it took me quite a while to figure out why these methods are available in RingoJS shell, but not in applications run using the standard method (it's because the ```binary``` module is - unnecessarily - loaded in ```io``` module, which is a dependency of ```ringo/term```).

Since we're heading towards 3.0 i propose to clean this up (and break backwards-compatibility), and replace it by ```binary.toByteArray(string)``` and ```binary.toByteString(string)```. An alternative could be to move these two methods into a separate string module or into the globals module (the latter would mean no changes to the java source), though i don't think that's necessary.

Please share your opinions.

**Comment by botic** [comment]
This should be located in the binary module and keep the overall count of modules the same. Never touch the String prototype 👍

**Comment by grob** [comment]
Never touch any of the standard prototypes ;-)
