### ISSUE TITLE
Reserved variable names in modules

### ISSUE THREAD

**Issue by grob** [ringo/ringojs#410]
More a documentation issue that i ran into recently: Rhino registers some toplevel java package names that one cannot use as variable names in a module using ```const``` - "java", "javax", "org", "com", "edu", "net". ([source](https://github.com/mozilla/rhino/blob/master/src/org/mozilla/javascript/ScriptRuntime.java#L298))

Trying to declare a variable ```const net = 123``` results in

`TypeError: TypeError: redeclaration of var net.`

I believe this should be documented, since i don't think we could circumvent this.

**Comment by botic** [comment]
Documented in https://github.com/ringo/ringojs.org/blob/master/site/documentation/modern_javascript.md
