### ISSUE TITLE
Is there a Babel preset for Ringo (Rhino?)

### ISSUE THREAD

**Issue by pastelmind** [ringo/ringojs#418]
I'd like to use modern ES features and transpile them. I can easily do so by using `@babel/preset-env` with no options to transpile everything down to ES5. However, it means I'm missing out on some ES2015 features that are already supported in Ringo, such as `for...of` loops, arrow functions, etc.

Is there a Babel preset specifically tailored for Ringo (Rhino)? Or perhaps a Babel alternative that can be configured to target Ringo?

**Comment by botic** [comment]
Not yet or not known, sorry.

**Comment by pastelmind** [comment]
I went and started https://github.com/pastelmind/babel-preset-rhino. Turns out it's a bigger hassle than I expected. **I need help.** Since RingoJS users may be interested in this project, I figured I'd ask here.

I created a Babel preset that piggybacks onto [@babel/preset-env](https://babeljs.io/docs/en/babel-preset-env). I intentionally omitted the [`targets`](https://babeljs.io/docs/en/babel-preset-env#targets) option, which turns on _all_ ES2015+ transformations. Then I disabled any plugins that Rhino doesn't need, such as [`transform-for-of`](https://babeljs.io/docs/en/babel-plugin-transform-for-of). I'm going through features listed on [Mozilla's compatibility tables](https://mozilla.github.io/rhino/compat/engines.html) and using a [test suite](https://github.com/pastelmind/babel-preset-rhino/tree/main/test) to verify that I'm only disabling transforms that I don't need.

Nearly all of the syntactic transforms are covered. I made some major assumptions, though, and I'd appreciate it if someone else reviewed them.

### Babel 7 required
I don't want to bother with older versions of Babel.

### Promises and async/await
Rhino does not natively support `setTimeout()`. Since most Polyfills for Promises rely on `setTimeout()`, they won't work either. I therefore skipped transpiling async/await features entirely.

❓ Question: I don't use RingoJS, but I understand it supports `setTimeout()` and a library version of Promise. Would you be interested in having async/await transpiled as well?

(Caveat: Babel doesn't know that RingoJS has to import `Promise` from `ringo/promise`. If async/await is polyfilled, RingoJS users would have to manually import `ringo/promise` in every file that uses async/await. Or perhaps write a custom Babel plugin for it.

### New RegExp flags
Since Rhino does not support the newer RegExp flags (`y`, `u`), I didn't bother transpiling them. **See below for more discussion.**

### Polyfills
I'm struggling with Babel's automatic polyfill import feature (enabled with [`useBuiltIns: 'usage'`](https://babeljs.io/docs/en/babel-preset-env#usebuiltins-usage)). For example, preset-env tries to polyfill `Object.keys()` even though Rhino supports it. I can easily disable this by excluding individual polyfill packages (`es.object.keys`). However, there are gotchas:

Some polyfills depend on each other. For example, the `es.string.split` polyfill is normally not needed, since Rhino already supports `String.prototype.split()`. However, if you want to use the `y` and `u` RegExp flags, `es.string.split` must be used along with `es.regexp.exec` to support them. I only discovered this after attempting to transpile `String.prototype.split()`. This is problematic because such dependencies are non-obvious.

❓ **How should I generate a set of polyfills that can be safely excluded, given that polyfills have hidden dependencies?**

**Comment by p-bakker** [comment]
Also see https://github.com/mozilla/rhino/issues/661 and https://github.com/babel/babel/pull/13448
