### ISSUE TITLE
What about alternative ScriptEngine?

### ISSUE THREAD

**Issue by CretinHo** [ringo/ringojs#419]
I mean Microsoft's Chakra Core: https://github.com/chakra-core/ChakraCore and Mozilla's SpiderMonkey: https://github.com/mozilla-spidermonkey/spidermonkey-embedding-examples

Mozilla has a standalone JSShell here: https://ftp.mozilla.org/pub/firefox/releases/78.1.0esr/jsshell/

Of course this will lost the ability to interop with Java, Ringo's most appealing feature. But they are alternative ScriptEngine, will not replace Rhino.

I read a bit about the history of Ringo and I think if it's anything but V8 (NodeJS), it will be fine to be considered, isn't it?

Rhino is too slow. Just test some toy js program on both Ringo and Mozilla's JSShell above and you will see how blazzing fast JSShell is compared to Rhino.

**Comment by botic** [comment]
RingoJS is a JVM-hosted runtime with full Java interoperability. We already had longer discussions about this around the time GraalVM came up and even back with Nashorn. That's why we clarified RingoJS' perspective:

> There are no plans to migrate to another JavaScript engine with a higher compatibility level. Ringo will be based on Rhino for the foreseeable future. Ringo follows the Rhino releases as soon as possible. New minor releases may be triggered by a new engine release with additional language features included.

https://ringojs.org/documentation/modern_javascript/
