### ISSUE TITLE
httpclient how to get data-csrf of a page?

### ISSUE THREAD

**Issue by CretinHo** [ringo/ringojs#420]
Seems I have to use JSoup to parse the HTML document to get data-csrf? Is there any built-in functions to do this? Thanks.

**Comment by botic** [comment]
The HTTP client has no HTML related functionality built-in. If you access a HTML page with a CSRF token in a form field, you must parse the returned content on your own.

The HTTP client is a basic implementation to load any resource available via HTTP or HTTPS. Most functionality is directly provided by [Java's URLConnection class](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/net/URLConnection.html) and Ringo's JavaScript code is an intelligent wrapper around it.

The HTTP client is not an HTML parser or something like [Puppeteer](https://pptr.dev/). It will just return the read content as string or binary data.

**Comment by CretinHo** [comment]
> The HTTP client has no HTML related functionality built-in. If you access a HTML page with a CSRF token in a form field, you must parse the returned content on your own.
> 
> The HTTP client is a basic implementation to load any resource available via HTTP or HTTPS. Most functionality is directly provided by [Java's URLConnection class](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/net/URLConnection.html) and Ringo's JavaScript code is an intelligent wrapper around it.
> 
> The HTTP client is not an HTML parser or something like [Puppeteer](https://pptr.dev/). It will just return the read content as string or binary data.

Seems I have to use JSoup :smile:
