### ISSUE TITLE
Where to ask questions about ringo and stick?

### ISSUE THREAD

**Issue by CretinHo** [ringo/ringojs#422]
The mailing list (google groups) is pretty much dead. Your twitter is pretty dead too with no new activities, no new updates... The only thing people left with is your API reference, some functions only listed but no explaination about what they do and how to use them. There are examples to demonstrate the API, but very few. I feel lost when reading this API reference. Where could I seek for help? Thanks.

**Comment by CretinHo** [comment]
Do you still check the google groups? Could I get answers from that place or should I just ask questions here?

**Comment by botic** [comment]
I think the best place will be here, since Google Groups are more or less dead. We might restructure our issues the make the response better, but having a single place for asking questions might be better than any scatterbrained mail-based threads.

**Comment by va0dl914** [comment]
@botic This repo is also a ghost town. BTW, go here help me persuading them pls: https://github.com/apache/netbeans/issues/4575
