### ISSUE TITLE
Rhino is too slow to be practically useful!

### ISSUE THREAD

**Issue by altPOCA** [ringo/ringojs#429]
As you stated here: https://github.com/ringo/ringojs/issues/419

You choose Rhino because of the Java ecosystem.

But if it's the JVM, no one will use such a language as JavaScript!

Let alone the performance of Rhino is too bad rendering it unrealistic in practical.

The code is proprietary. I do not own it so I can't post here but I can only reveal with you.

On the Chromium Developer console, it tooks about seconds to complete.

With the Mozilla JSShell here: https://ftp.mozilla.org/pub/firefox/releases/78.1.0esr/jsshell/

It's a bit slower but still about seconds.

But with Ringo, it tooks more than 15 mins and still running! It seems it will never complete. I have to cancel it.

The code is heavy on numeric operations. Google's V8 engine is incredible, it's even faster than the optimized O3 C++ version!

V8 is the future. Node is the way to go. Bye.

**Comment by botic** [comment]
If you look for a fast JavaScript runtime, don't approach Rhino / Ringo. The primary goal is to incorporate the power of Java libraries and solid frameworks.

**Comment by altPOCA** [comment]
Stop to be toxic! This should be considered as a regression, a serious bug of Rhino itself. Do you know QuickJS?

https://bellard.org/quickjs/

It's an interpreter, much slower than JS VM like Rhino (JVM). But guess what? QuickJS completed the task after more than five minutes, and RingoJS still keeps running after 15 mins without any signs of it will ever complete. I have to cancel the process.

Get it? Plain Java completed the task about 9 seconds. PHP, completed the task about 1min22s.

Just because I don't know which version of Rhino you shipped with RingoJS 2.0 so I didn't report the bug to the Rhino project. If I know, I already fired them a bug report.

**Comment by botic** [comment]
Please also take a look at [the documentation](https://ringojs.org/documentation/modern_javascript/):

> There are no plans to migrate to another JavaScript engine with a higher compatibility level. Ringo will be based on Rhino for the foreseeable future. Ringo follows the Rhino releases as soon as possible. New minor releases may be triggered by a new engine release with additional language features included.

We will not change the underlying engine in Ringo now, or in the next releases. This would be an intensive rewrite of the whole core and is not feasible. We don't have the time or capacity to do this.

If your code is slow on Rhino, please consider another runtime. We will not change this and it is not worth your time to go into this topic. Ringo is Rhino-based, no matter what will happen around.
