### ISSUE TITLE
Ringo 3.0.0 release ballot

### ISSUE THREAD

**Issue by botic** [ringo/ringojs#430]
This issue tracks the release of Ringo 3.0.0. There is a first release candidate:
https://github.com/ringo/ringojs/releases/tag/v3.0.0-RC1

Please test it in your local environments and maybe even in smaller production environments. If you don't find any blocking issues, please also comment in this issue.

To release this version, at least @grob and @oberhamsi must approve in this ballot.

**Comment by altPOCA** [comment]
Please add to this page that you don't have support for class based OOP of modern JavaScript so people seeking for a JS Platform don't settle on the wrong side:

https://ringojs.org/documentation/modern_javascript/

All of us learned JS from books, tutorials and online curriculums learned the class based OOP of ECMA 2015 and even some sites teach the latest newest features of ECMA 2020. So they will not be disappointed and feel they are being betrayed by you.

Explicitly state they you still on prototypal OOP.

Last but not least, this release of yours worked fine with NetBeans IDE. You could use the project type NodeJS Application and ignore any errors it spits out about missing of NodeJS. Code completion works beautifully and there is no parsing errors.

I found NetBeans to be a perfect pal for Ringo. You could put it on the list of working IDE for Ringo.

I personally can't stand the old JS syntax of Ringo so even though I liked the design of it (especially workers and multithreading) I will go with Node. Bye. Will not annoying you anymore.

**Comment by botic** [comment]
Blocked by #431

**Comment by botic** [comment]
I think we will wait ~ 2 more weeks and test the current master for the final 3.x release. #431 has been fixed, but I had no time to test the current master with my production applications so far and I guess the people at ORF also want to test it on their systems.

**Comment by botic** [comment]
I suggest a renaming to `main` with the release, see #447

**Comment by botic** [comment]
I think we are done for 3.0.0. #439 should be on our radar, but it can be moved out of this release.

**Comment by grob** [comment]
LGTM 🚢 it!

**Comment by oberhamsi** [comment]
Looks good!

**Comment by botic** [comment]
Released.
