### ISSUE TITLE
Deprecate & remove the current package system

### ISSUE THREAD

**Issue by botic** [ringo/ringojs#434]
I saw a lot of troubles around packages and package management with `rp` in the last days. As important users like @orfon are not relying on `rp` and packages.ringojs.org, we should talk about the future of the package system.

Ringo's `rp` has been around for quite a long time. It emerged together with the first iterations of npm. Ignoring the current Node ecosystem and npm, `rp` still solves the some problems. Though, package management and resolving the right versions never played an important role for our ecosystem. Mostly we all know the exact version we need and don't need advanced resolution.

Jumping into the world of today, I see some work in front of us, if we want to continue to support `rp` with future releases:

1. Update `rp` to work with the current 3.0 release candidates.
2. Ensure packages are compatible with the next releases, if they get installed with a package manager.
3. Improve documentation and keep `packages.ringojs.org`.
4. Fix the current `ringo-admin` tool for installing packages and the built-in skeletons.

From my perspective maintaining these parts slows us down. It is not our priority to have a package management system around. RingoJS needs a package format, but not a whole system around it.

Therefore I asked for your opinions and thoughs about removing `rp` from the documentation and to replace `ringo-admin` with a better tool for installing packages from URLs (defined in a `package.json`, or directly via the CLI).

**Comment by grob** [comment]
👍 for deprecating/dropping rp (incl. packages.ringojs.org). installing packages from URLs without any dependency resolution step sounds sane to me, but i think the package installer should also support git cloning via http/ssh (git resp. git+ssh scheme).

**Comment by botic** [comment]
I think this is done. I updated the documentation as good as possible. Or @grob?

**Comment by grob** [comment]
Sure, i'll close it

**Comment by grob** [comment]
I believe we should update the readme too, it still mentiones rp

**Comment by botic** [comment]
Should be removed on all known places. With the release of 3.0 we will need to pull ringojs.org to the latest version.
