### ISSUE TITLE
`this` refers neither to the global `this` nor to `undefined`

### ISSUE THREAD

**Issue by Melab** [ringo/ringojs#440]
At least in RingoJS 3.0.0 RC3's REPL, the value of `this` refers is neither the global `this` nor `undefined`. Instead, it's an object with the following non-inherited properties:

+ `__GeneratorFunction`.
+ `module`.
+ `exports`.
+ `constructor`.
+ `importClass`.
+ `importPackage`.

Perhaps the reason `this` does not refer to the global `this` is because the REPL is running inside its own module scope or something. Although crippling, it would be understandable if `this` took on the value `undefined`. Instead, it's a non-standard object which certainly should not have `module` and `exports` properties as they are supposed to be unparented local variables in a CommonJS module scope.

**Comment by botic** [comment]
`this` in a REPL always points to a module scope bound to the working directory. You can access the global object via `global`, but not via `this`. 

> Every JavaScript file is treated a module living in its own top-level scope.

So this is the expected behavior.

**Comment by botic** [comment]
I closed the issue since this *is* the expected `this` in the REPL.
