### ISSUE TITLE
Error encountered while running gradlew

### ISSUE THREAD

**Issue by Melab** [ringo/ringojs#441]
I have attached the output of running `./gradlew` to compile RingoJS. The commit ID is [8c901871...59c7e9a7](https://github.com/ringo/ringojs/tree/8c9018711035cbeec49962d18b7f241659c7e9a7).  The build fails because of a deprecated Java method.

I am using Java 11 version of OpenJDK.

[tee.log](https://github.com/ringo/ringojs/files/7730489/tee.log)

**Comment by grob** [comment]
Looks more like a timing issue in `test/ringo/concurrent_test.js` - building was successfull on my machine, but it might help to increase the 60ms timeout in `semaphore.tryWait(60, 2)`.

**Comment by Melab** [comment]
> Looks more like a timing issue in `test/ringo/concurrent_test.js` - building was successfull on my machine, but it might help to increase the 60ms timeout in `semaphore.tryWait(60, 2)`.

I had to increase the timeout to 300 milliseconds for those tests involving it to pass, but it failed elsewhere.

**Comment by grob** [comment]
sorry, can't reproduce (os x 10.15.7 using AdoptOpenJDK build 11.0.9+11), even without increasing the timeout - could you post the stacktrace or any other additional hints **where** the build fails?

**Comment by Melab** [comment]
> sorry, can't reproduce (os x 10.15.7 using AdoptOpenJDK build 11.0.9+11), even without increasing the timeout - could you post the stacktrace or any other additional hints **where** the build fails?

I was mistaken. It failed on the same tests.

I'll post the log later.

**Comment by botic** [comment]
Closed after inactivity.
